services:
  - type: web
    name: barber-backend
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false  # Set this in Render dashboard
      - key: JWT_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        sync: false  # Set this in Render dashboard
      - key: VAPID_PUBLIC_KEY
        sync: false  # Set this in Render dashboard
      - key: VAPID_PRIVATE_KEY
        sync: false  # Set this in Render dashboard
      - key: VAPID_SUBJECT
        sync: false  # Set this in Render dashboard